name: Build and test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.17']
        # ARCH: consider macos (hit timeout issues), consider pinning
        os: [ubuntu-latest, windows-latest]
    name: Go ${{ matrix.go }}@${{ matrix.os }} test run
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Test
      run: make test
    
    - name: Test (race)
      run: make test-race

    - name: Build
      run: make build
